compact: true
directory:
- charts/outfinity-gift
download-external-modules: false
evaluate-variables: true
external-modules-download-path: .external_modules
framework:
- helm
quiet: true
soft-fail: true
var-file:
- .checkov/outfinity-gift/values.yaml
output: cli
