{{- if .Values.pdfConverter.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "outfinity-gift.fullname" . }}-pdf-converter
  namespace: {{ template "outfinity-gift.namespace" . }}
  labels:
    {{- include "outfinity-gift.labels" . | nindent 4 }}
    app.kubernetes.io/component: pdf-converter
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "outfinity-gift.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: pdf-converter
  template:
    metadata:
      {{- with .Values.pdfConverter.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "outfinity-gift.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: pdf-converter
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "outfinity-gift.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.pdfConverter.podSecurityContext | nindent 8 }}
      containers:
        - name: pdf-converter
          securityContext:
            {{- toYaml .Values.pdfConverter.securityContext | nindent 12 }}
          image: "{{ .Values.pdfConverter.image.repository }}:{{ .Values.pdfConverter.image.tag }}"
          imagePullPolicy: {{ .Values.pdfConverter.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.pdfConverter.service.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.pdfConverter.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.pdfConverter.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.pdfConverter.resources | nindent 12 }}
          volumeMounts:
            - name: storage-volume
              mountPath: /app/storage
          env:
            - name: STORAGE_DIR
              value: "/app/storage"
      volumes:
        - name: storage-volume
          persistentVolumeClaim:
            claimName: {{ include "outfinity-gift.fullname" . }}-pdf-converter
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- else }}
# Debug: .Values.pdfConverter is {{ .Values.pdfConverter | quote }}
{{- end }}