apiVersion: v1
kind: Service
metadata:
  name: s3-adapter
  labels:
    app: s3-adapter
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.s3AdapterConfig.port }}
      targetPort: {{ .Values.s3AdapterConfig.port }}
      protocol: TCP
      name: s3-adapter-http
  selector:
    app: s3-adapter
